In [10]:
import numpy as np

Exercise 1:
1. Create a NumPy array of size 4x3 and filled with random numbers from 10 to 98 (inclusive). Calculate the sum of all elements, the sum of each row and each column.

In [18]:
ex1_array = np.random.randint(10, 99, (4, 3))
print(ex1_array)
print(ex1_array.sum(axis=1))
print(ex1_array.sum(axis=0))
print(ex1_array.sum())


[[98 58 60]
 [69 52 21]
 [33 14 17]
 [82 44 23]]
[216 142  64 149]
[282 168 121]
571


Exercise 2:
1. Create a NumPy array of size 10 filled with random numbers from 0 to 10. Count how many of them are even numbers.

In [44]:
ex2_array = np.random.randint(0, 10, 10)

[4 8 0 7 3 0 9 6 9 7]


In [48]:
filtered_array = ex2_array[ex2_array % 2 == 0]
print(len(filtered_array))

5


Exercise 3:
1. Create a NumPy array of size 100, filled with a sequence of numbers from 0 to 99.
2. Reshape this array into 10 rows and 10 columns.
3. Replace all values in the array which are greater than 50 with -1.
4. Calculate the sum of all elements in the array.
5. Calculate the mean of all elements in the array

In [52]:
ex3_array = np.random.randint(0, 99, 100)
print(ex3_array)

[59 19 66 20 74  8 54 78 31 74 53 84 17 33  8 76 46 92 43 85 72 33 31 43
  6 48 82 26 75 45 82 93 82 76 48 52 39 62 52 57 48 40 19 59 54 10 76 48
 39 32 19 59 81 77 22 61  3 24 96 36 63 85 24  7 83 69  0 57 70 81 46 63
 38 97 96 23 84 50 84 65  9 69 18 23 87 16 73 95 28 62 73 76  7  4 60 71
 11 81 87 77]


In [56]:
print(ex3_array.reshape(10, 10))


[[59 19 66 20 74  8 54 78 31 74]
 [53 84 17 33  8 76 46 92 43 85]
 [72 33 31 43  6 48 82 26 75 45]
 [82 93 82 76 48 52 39 62 52 57]
 [48 40 19 59 54 10 76 48 39 32]
 [19 59 81 77 22 61  3 24 96 36]
 [63 85 24  7 83 69  0 57 70 81]
 [46 63 38 97 96 23 84 50 84 65]
 [ 9 69 18 23 87 16 73 95 28 62]
 [73 76  7  4 60 71 11 81 87 77]]


In [62]:
ex3_array[ex3_array > 50] = -1
print(ex3_array)

[-1 19 -1 20 -1  8 -1 -1 31 -1 -1 -1 17 33  8 -1 46 -1 43 -1 -1 33 31 43
  6 48 -1 26 -1 45 -1 -1 -1 -1 48 -1 39 -1 -1 -1 48 40 19 -1 -1 10 -1 48
 39 32 19 -1 -1 -1 22 -1  3 24 -1 36 -1 -1 24  7 -1 -1  0 -1 -1 -1 46 -1
 38 -1 -1 23 -1 50 -1 -1  9 -1 18 23 -1 16 -1 -1 28 -1 -1 -1  7  4 -1 -1
 11 -1 -1 -1]


In [64]:
ex3_array.sum()

1133

In [66]:
ex3_array.mean()

11.33

Exercise 4:
1. Create an array of 10 elements with numbers between 0 -100 with the same space between each element.
2. Generate a new array that has all values from the previous array that are greater than 50 or lower than 20.
3. Reshape the array to a matrix array possible, (for example if its possible to reshape the array to 4X3 matrix generate it)

In [68]:
ex4_array = np.linspace(0, 100, 10)
print(ex4_array)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [70]:
new_array = ex4_array[(ex4_array > 50) | (ex4_array < 20)]
print(new_array)

[  0.          11.11111111  55.55555556  66.66666667  77.77777778
  88.88888889 100.        ]


In [72]:
new_array.reshape(4,3)

ValueError: cannot reshape array of size 7 into shape (4,3)

Exercise 5:
1. Generate a matrix of 4x4 filled with 0, make sure the type of them is int type.
2. Change the first element, the last element and the center element to a different random value between 10 - 100.

In [86]:
ex5_array = np.zeros((4,4), dtype= int)
print(ex5_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [100]:
ex5_array[0, 0] = np.random.randint(10, 101)
ex5_array[3, 3] = np.random.randint(10, 101)
ex5_array[1, 3] = np.random.randint(10, 101)

In [102]:
print(ex5_array)

[[28  0  0  0]
 [ 0  0  0 98]
 [ 0  0  0  0]
 [ 0  0  0 22]]
